/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "Algorithim.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Timed, Timed, AUTO)


PB_BIND(Counted, Counted, AUTO)


PB_BIND(SpikeStart, SpikeStart, AUTO)


PB_BIND(Bouncing, Bouncing, AUTO)


PB_BIND(BouningRep, BouningRep, AUTO)


PB_BIND(BounceMeasurment, BounceMeasurment, AUTO)


PB_BIND(AlgorithimConfiguration, AlgorithimConfiguration, AUTO)


PB_BIND(Rep, Rep, AUTO)


PB_BIND(Transfer, Transfer, AUTO)



