# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: algorithim.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61lgorithim.proto\"\x19\n\x05Timed\x12\x10\n\x08\x64uration\x18\x01 \x01(\r\"\x19\n\x07\x43ounted\x12\x0e\n\x06\x63ounts\x18\x01 \x01(\r\"\x0c\n\nSpikeStart\"\x19\n\x08\x42ouncing\x12\r\n\x05jumps\x18\x01 \x01(\r\"n\n\nBouningRep\x12\x15\n\raverageHeight\x18\x01 \x01(\r\x12 \n\x18\x61verageGroundContactTime\x18\x02 \x01(\r\x12\'\n\x0cmeasurements\x18\x03 \x03(\x0b\x32\x11.BounceMeasurment\"=\n\x10\x42ounceMeasurment\x12\x19\n\x11groundContactTime\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\"\xa8\x01\n\x17\x41lgorithimConfiguration\x12\x17\n\x05timed\x18\x01 \x01(\x0b\x32\x06.TimedH\x00\x12!\n\nspikeStart\x18\x02 \x01(\x0b\x32\x0b.SpikeStartH\x01\x12\x1d\n\x08\x62ouncing\x18\x03 \x01(\x0b\x32\t.BouncingH\x02\x42\x0f\n\rendAlgorithimB\x10\n\x0estartAlgorthimB\x0f\n\rconfiguration\"/\n\x03Rep\x12!\n\nbouningRep\x18\x01 \x01(\x0b\x32\x0b.BouningRepH\x00\x42\x05\n\x03rep\"Z\n\x08Transfer\x12.\n\nAlgorithim\x18\x01 \x01(\x0b\x32\x18.AlgorithimConfigurationH\x00\x12\x13\n\x03rep\x18\x02 \x01(\x0b\x32\x04.RepH\x00\x42\t\n\x07messageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'algorithim_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIMED._serialized_start=20
  _TIMED._serialized_end=45
  _COUNTED._serialized_start=47
  _COUNTED._serialized_end=72
  _SPIKESTART._serialized_start=74
  _SPIKESTART._serialized_end=86
  _BOUNCING._serialized_start=88
  _BOUNCING._serialized_end=113
  _BOUNINGREP._serialized_start=115
  _BOUNINGREP._serialized_end=225
  _BOUNCEMEASURMENT._serialized_start=227
  _BOUNCEMEASURMENT._serialized_end=288
  _ALGORITHIMCONFIGURATION._serialized_start=291
  _ALGORITHIMCONFIGURATION._serialized_end=459
  _REP._serialized_start=461
  _REP._serialized_end=508
  _TRANSFER._serialized_start=510
  _TRANSFER._serialized_end=600
# @@protoc_insertion_point(module_scope)
