/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "Algorithim.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Exercise, Exercise, AUTO)


PB_BIND(RollingAlgorithim, RollingAlgorithim, AUTO)


PB_BIND(AlgorithimConfiguration, AlgorithimConfiguration, AUTO)




